### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by egregors** [egregors/sucker#11]
```
goroutine 317 [running]:
github.com/egregors/sucker/app/internal.(*Worker).retry.func1(0xc00054e640, 0xc00010e068)
	/Users/egregors/Documents/Github/sucker/app/internal/worker.go:50 +0x50
created by github.com/egregors/sucker/app/internal.(*Worker).retry
	/Users/egregors/Documents/Github/sucker/app/internal/worker.go:48 +0x56
```

**Comment by egregors** [comment]
```
_downloads
135 / 143 [--------------------------------------------------->___] 94.41% 0 p/s
panic: send on closed channel

goroutine 210 [running]:
github.com/egregors/sucker/app/internal.(*Worker).retry.func1(0xc000020240, 0xc00047f140)
	/Users/egregors/Documents/Github/sucker/app/internal/worker.go:65 +0x50
created by github.com/egregors/sucker/app/internal.(*Worker).retry
	/Users/egregors/Documents/Github/sucker/app/internal/worker.go:63 +0x56
```

**Comment by egregors** [comment]
```
goroutine 389 [running]:
github.com/egregors/sucker/app/internal.(*Worker).retry.func1(0xc00085e140, 0xc0005f62d0)
	/Users/egregors/Documents/GitHub/sucker/app/internal/worker.go:65 +0x50
created by github.com/egregors/sucker/app/internal.(*Worker).retry
	/Users/egregors/Documents/GitHub/sucker/app/internal/worker.go:63 +0x56
```
